@php
    $itemData = is_array($item) ? $item : $item->toArray();
    $selectedItem = $fieldValue($dotPrefix.'.catalog_item_id', $itemData['catalog_item_id'] ?? '');
    $originalItem = $legacy && isset($legacyOriginals[$itemData['id'] ?? '']) ? $legacyOriginals[$itemData['id']] : $itemData;
    $originalQuantity = is_scalar($originalItem['quantity'] ?? null) ? (string) $originalItem['quantity'] : '0.00';
    $originalTotal = is_scalar($originalItem['total_amount'] ?? null) ? (string) $originalItem['total_amount'] : '';
@endphp
<tr data-bidding-item data-entry-index="{{ $index }}" data-name-prefix="{{ $namePrefix }}" data-legacy="{{ $legacy ? 'true' : 'false' }}" data-original-quantity="{{ $originalQuantity }}" data-original-total="{{ $originalTotal }}">
    <td class="space-y-2 px-3 py-3 align-top">
        @if(!empty($itemData['id']) && is_scalar($itemData['id']))<input type="hidden" name="{{ $namePrefix }}[id]" value="{{ $itemData['id'] }}">@endif
        <label for="{{ $uid }}-search" class="sr-only">Search catalog</label><input id="{{ $uid }}-search" type="search" data-catalog-search autocomplete="off" placeholder="Search catalog?" class="w-full rounded-md border-slate-200 py-1.5 text-xs focus:border-blue-500 focus:ring-blue-500">
        <label for="{{ $uid }}-catalog" class="sr-only">Catalog item</label><select id="{{ $uid }}-catalog" name="{{ $namePrefix }}[catalog_item_id]" data-catalog-item @required(!$legacy) class="w-full rounded-md border-slate-200 py-1.5 text-xs focus:border-blue-500 focus:ring-blue-500"><option value="">{{ $legacy ? 'Keep saved item' : 'Select catalog item' }}</option>@foreach($catalogItems as $catalogItem)<option value="{{ $catalogItem->id }}" data-description="{{ $catalogItem->description ?: $catalogItem->item_name }}" data-unit="{{ $catalogItem->unit }}" data-price="{{ $catalogItem->price }}" @selected($selectedItem === (string) $catalogItem->id)>{{ $catalogItem->item_name }}{{ $catalogItem->active ? '' : ' (inactive)' }}</option>@endforeach</select>
        <span data-catalog-message role="status" class="block text-xs text-slate-500"></span>
        <label for="{{ $uid }}-description" class="sr-only">Item description</label><textarea id="{{ $uid }}-description" name="{{ $namePrefix }}[item_description]" data-item-description rows="2" maxlength="10000" class="w-full rounded-md border-slate-200 text-xs focus:border-blue-500 focus:ring-blue-500" placeholder="Item description">{{ $fieldValue($dotPrefix.'.item_description', $itemData['item_description'] ?? '') }}</textarea>
        <x-input-error :messages="$errors->get($dotPrefix.'.catalog_item_id')" class="text-xs" /><x-input-error :messages="$errors->get($dotPrefix.'.item_description')" class="text-xs" />
    </td>
    <td class="px-2 py-3 align-top"><label for="{{ $uid }}-unit" class="sr-only">Unit</label><input id="{{ $uid }}-unit" name="{{ $namePrefix }}[unit]" data-item-unit value="{{ $fieldValue($dotPrefix.'.unit', $itemData['unit'] ?? '') }}" maxlength="50" class="w-full rounded-md border-slate-200 py-1.5 text-xs focus:border-blue-500 focus:ring-blue-500"><x-input-error :messages="$errors->get($dotPrefix.'.unit')" class="text-xs" /></td>
    <td class="px-2 py-3 align-top"><label for="{{ $uid }}-quantity" class="sr-only">Quantity</label><input id="{{ $uid }}-quantity" name="{{ $namePrefix }}[quantity]" data-item-quantity type="number" min="0" max="9999999999999.99" step="0.01" required value="{{ $fieldValue($dotPrefix.'.quantity', $itemData['quantity'] ?? '1') }}" class="w-full rounded-md border-slate-200 py-1.5 text-xs focus:border-blue-500 focus:ring-blue-500"><x-input-error :messages="$errors->get($dotPrefix.'.quantity')" class="text-xs" /></td>
    <td class="px-2 py-3 align-top"><label for="{{ $uid }}-cost" class="sr-only">Unit cost in PHP</label><input id="{{ $uid }}-cost" name="{{ $namePrefix }}[unit_cost]" data-item-cost type="number" min="0" max="9999999999999.99" step="0.01" @required(!$legacy) value="{{ $fieldValue($dotPrefix.'.unit_cost', $itemData['unit_cost'] ?? '') }}" class="w-full rounded-md border-slate-200 py-1.5 text-xs focus:border-blue-500 focus:ring-blue-500"><span data-item-price-message class="mt-1 block text-xs text-amber-800"></span><x-input-error :messages="$errors->get($dotPrefix.'.unit_cost')" class="text-xs" /></td>
    <td class="px-2 py-3 align-top"><label for="{{ $uid }}-amount" class="sr-only">Calculated amount in PHP</label><input id="{{ $uid }}-amount" name="{{ $namePrefix }}[total_amount]" data-item-total type="text" readonly value="{{ $fieldValue($dotPrefix.'.total_amount', $itemData['total_amount'] ?? '') }}" class="w-full rounded-md border-slate-200 bg-slate-50 py-1.5 font-mono text-xs tabular-nums text-slate-700"><x-input-error :messages="$errors->get($dotPrefix.'.total_amount')" class="text-xs" /></td>
    <td class="px-2 py-3 align-top"><label for="{{ $uid }}-brand" class="sr-only">Brand or specifications</label><input id="{{ $uid }}-brand" name="{{ $namePrefix }}[brand]" value="{{ $fieldValue($dotPrefix.'.brand', $itemData['brand'] ?? '') }}" maxlength="255" class="w-full rounded-md border-slate-200 py-1.5 text-xs focus:border-blue-500 focus:ring-blue-500"></td>
    <td class="px-2 py-3 align-top"><label for="{{ $uid }}-remarks" class="sr-only">Item remarks</label><textarea id="{{ $uid }}-remarks" name="{{ $namePrefix }}[remarks]" rows="2" maxlength="10000" class="w-full rounded-md border-slate-200 text-xs focus:border-blue-500 focus:ring-blue-500">{{ $fieldValue($dotPrefix.'.remarks', $itemData['remarks'] ?? '') }}</textarea><x-input-error :messages="$errors->get($dotPrefix.'.remarks')" class="text-xs" /></td>
    <td class="px-2 py-3 align-top"><button type="button" data-bidding-action="remove-item" class="rounded-md px-2 py-1.5 text-xs font-semibold text-red-600 hover:bg-red-50" aria-label="Remove item">Remove</button></td>
</tr>
