<x-accounting_app>
    <x-slot name="header">{{ $travel ? 'Travel Liquidation' : 'Budget Request' }} · {{ $budget->control_id }}</x-slot>
    <div class="space-y-5">
        @if(session('status'))<p class="rounded-lg bg-green-50 p-4 text-sm text-green-800">{{ session('status') }}</p>@endif
        @if($errors->any())<p class="rounded-lg bg-red-50 p-4 text-sm text-red-800">{{ $errors->first() }}</p>@endif
        <section class="rounded-2xl border bg-white p-5"><div class="flex flex-wrap justify-between gap-3"><h1 class="text-xl font-bold">{{ $budget->control_id }}@if($travel) · Travel #{{ $travel->id }}@endif</h1><span class="rounded-lg bg-blue-50 px-3 py-1 text-sm text-blue-700">{{ str_replace('_', ' ', $travel?->status ?? $budget->status) }}</span></div><dl class="mt-5 grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-3">@foreach(['Requester' => $budget->employee?->name, 'Company' => $budget->company?->name, 'Department' => $budget->department, 'Position' => $budget->employee?->position, 'Request date' => $budget->created_at?->format('M d, Y'), 'Requested amount (currency unspecified)' => $budget->budget_total] as $label => $value)<div><dt class="text-xs text-slate-500">{{ $label }}</dt><dd class="mt-1 font-semibold">{{ $value ?? 'Not recorded' }}</dd></div>@endforeach</dl><p class="mt-5 text-sm"><strong>Purpose:</strong> {{ $budget->objectives ?? 'Not recorded' }}</p><p class="mt-2 text-sm"><strong>Remarks:</strong> {{ $budget->remarks ?? 'Not recorded' }}</p><p class="mt-2 text-xs text-slate-500">Project links, budget attachments, and separate manager decision comments are not stored. Recorded approval stamps and actual activity comments appear below.</p></section>
        <section class="rounded-2xl border bg-white p-5"><h2 class="font-bold">Recorded releases</h2>@forelse($budget->releases as $release)<p class="mt-3 text-sm">{{ $release->currency }} {{ $release->amount }} · {{ $release->payment_method }} · {{ $release->reference_no }} · {{ $release->released_at }}<br>{{ $release->note }}</p>@empty<p class="mt-3 text-sm text-slate-500">No quantified release evidence recorded.@if($budget->released_at) Unquantified confirmation: {{ $budget->released_at }}.@endif</p>@endforelse<p class="mt-3 text-sm">Employee acknowledgment: {{ $budget->received_at ?? 'Awaiting employee acknowledgment' }}</p></section>
        <section class="overflow-hidden rounded-2xl border bg-white"><h2 class="p-5 font-bold">{{ $travel ? 'Actual expenses' : 'Requested expenses' }}</h2><div class="overflow-x-auto"><table class="w-full min-w-[700px] text-left text-sm"><thead class="bg-slate-50"><tr>@foreach(['Category', 'Description', 'Cash', 'Card', 'Travel agent', 'Total', 'Receipt'] as $heading)<th class="p-3">{{ $heading }}</th>@endforeach</tr></thead><tbody>@forelse(($travel?->items ?? $budget->items) as $item)<tr class="border-t"><td class="p-3">{{ $item->expense_category }}</td><td class="p-3">{{ $item->particular }}</td>@foreach(($travel ? ['actual_cash', 'actual_credit_card', 'actual_travel_agent', 'actual_total'] : ['budget_cash', 'budget_credit_card', 'budget_travel_agent', 'budget_total']) as $field)<td class="p-3 font-mono">{{ $item->$field }}</td>@endforeach<td class="p-3">{{ $travel ? match($item->receipt_attached) { 'yes' => 'Declared attached; file verification unavailable', 'no' => 'Missing receipt', default => 'Not applicable' } : 'No attachment model' }}</td></tr>@empty<tr><td class="p-5" colspan="7">No itemized expenses.</td></tr>@endforelse</tbody></table></div><p class="p-4 text-xs text-slate-500">Expense currency and per-line travel dates are not persisted. Cash, card and agent expenses do not independently establish employee cash owed.</p></section>
        @if($travel)
            <section class="rounded-2xl border bg-white p-5"><h2 class="font-bold">Settlement evidence</h2>@if($travel->settlement)<dl class="mt-4 grid gap-3 text-sm sm:grid-cols-2">@foreach(['released_amount', 'expense_amount', 'employee_return_amount', 'company_reimbursement_amount', 'outstanding_balance'] as $field)<div><dt class="text-xs text-slate-500">{{ ucfirst(str_replace('_', ' ', $field)) }}</dt><dd class="font-mono">{{ $travel->settlement->currency }} {{ $travel->settlement->$field }}</dd></div>@endforeach</dl><p class="mt-3 text-sm">{{ $travel->settlement->reference_no }} · {{ $travel->settlement->settled_at }}</p>@else<p class="mt-3 text-sm text-slate-500">No settlement payment recorded. Budget variance {{ $travel->variance }} is informational and does not prove a return or reimbursement.</p>@endif</section>
            @can('noteByAccounting', $travel) @if($travel->status === 'submitted')<form method="POST" action="{{ route('travel_liquidation.note', $travel) }}" onsubmit="return confirm('Record Accounting review for this liquidation?')">@csrf<button class="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Accept Accounting review</button></form>@endif @endcan
            @include('mi_app.financial_history', ['activities' => $travel->activities])
            <p class="text-xs text-slate-500">Settlement recording and closure use the existing controlled workflow. @if(!config('mi_financial.settlement_recording_enabled'))Settlement recording is disabled pending confirmed payment rules.@endif Return for correction is not enabled.</p>
        @else
            <div class="flex flex-wrap gap-3">
                @can('noteByAccounting', $budget) @if($budget->status === 'approved' && !$budget->noted_at)<form method="POST" action="{{ route('budget_requests.note', $budget) }}" onsubmit="return confirm('Record the Accounting note for this request?')">@csrf<button class="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Record Accounting note</button></form>@endif @endcan
                @can('release', $budget) @if($budget->status === 'approved' && $budget->noted_at && $budget->noted_by && !$budget->released_at)
                    <form method="POST" action="{{ route('budget_requests.release', $budget) }}" onsubmit="return confirm('Confirm this fund release?')" class="w-full rounded-xl border p-4">@csrf
                        @if(config('mi_financial.release_recording_enabled'))<div class="grid gap-3 sm:grid-cols-2">@foreach(['amount' => 'Actual release amount', 'payment_method' => 'Release method', 'reference_no' => 'Payment reference'] as $name => $label)<label class="text-sm">{{ $label }}<input required name="{{ $name }}" value="{{ old($name) }}" class="mt-1 block w-full rounded-lg border-slate-200"></label>@endforeach<label class="text-sm">Currency<select required name="currency" class="mt-1 block w-full rounded-lg border-slate-200">@foreach(config('mi_financial.currencies', []) as $currency)<option>{{ $currency }}</option>@endforeach</select></label><label class="text-sm">Accounting note<textarea name="note" class="mt-1 block w-full rounded-lg border-slate-200">{{ old('note') }}</textarea></label></div>@else<p class="mb-3 text-sm text-amber-800">This records an unquantified release confirmation only. No requested amount is copied into a payment record.</p>@endif
                        <button class="mt-3 rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white">{{ config('mi_financial.release_recording_enabled') ? 'Record actual release' : 'Confirm unquantified release' }}</button>
                    </form>
                @endif @endcan
            </div>
        @endif
        <section class="rounded-2xl border bg-white p-5"><h2 class="font-bold">Recorded workflow stamps</h2><p class="mt-3 text-sm">Approval: {{ $budget->approved_at ?? 'Awaiting designated approver' }} · Accounting note: {{ $budget->noted_at ?? 'Not recorded' }} · Release: {{ $budget->released_at ?? 'Not recorded' }}</p>@if($travel)<p class="mt-2 text-sm">Submitted: {{ $travel->submitted_at ?? 'Not recorded' }} · Review: {{ $travel->noted_at ?? 'Not recorded' }} · Final approval: {{ $travel->approved_at ?? 'Not recorded' }}</p>@endif</section>
        @include('mi_app.financial_history', ['activities' => $budget->activities])
        @if($budget->liquidation && !$travel)@can('viewProcessing', $budget->liquidation)<a class="inline-block text-sm font-semibold text-blue-700" href="{{ route('accounting.mi.travel.show', $budget->liquidation) }}">Open linked travel liquidation →</a>@endcan @endif
        @if($travel)<a class="inline-block text-sm font-semibold text-blue-700" href="{{ route('travel_liquidation.processing', $travel) }}">Open permitted approval, settlement and closure actions →</a>@endif
    </div>
</x-accounting_app>
