<form method="GET" class="grid grid-cols-1 gap-3 border-b border-slate-100 p-5 sm:grid-cols-2 xl:grid-cols-4">
    <label class="text-xs font-semibold text-slate-500">Reference<input name="reference" value="{{ $filters['reference'] ?? '' }}" maxlength="255" class="mt-1 block w-full rounded-lg border-slate-200 text-sm" placeholder="Reference or report title"></label>
    <label class="text-xs font-semibold text-slate-500">Employee<select name="employee" class="mt-1 block w-full rounded-lg border-slate-200 text-sm"><option value="">All employees</option>@foreach($queueEmployees as $employee)<option value="{{ $employee->user_id }}" @selected(($filters['employee'] ?? '') == $employee->user_id)>{{ $employee->name }}</option>@endforeach</select></label>
    <label class="text-xs font-semibold text-slate-500">Department<input name="department" value="{{ $filters['department'] ?? '' }}" maxlength="100" class="mt-1 block w-full rounded-lg border-slate-200 text-sm"></label>
    <label class="text-xs font-semibold text-slate-500">Type<select name="type" class="mt-1 block w-full rounded-lg border-slate-200 text-sm"><option value="">All types</option>@foreach(['budget' => 'Budget', 'travel' => 'Travel liquidation', 'ordinary' => 'Ordinary liquidation'] as $value => $label)<option value="{{ $value }}" @selected(($filters['type'] ?? '') === $value)>{{ $label }}</option>@endforeach</select></label>
    <label class="text-xs font-semibold text-slate-500">From<input type="date" name="date_from" value="{{ $filters['date_from'] ?? '' }}" class="mt-1 block w-full rounded-lg border-slate-200 text-sm"></label>
    <label class="text-xs font-semibold text-slate-500">To<input type="date" name="date_to" value="{{ $filters['date_to'] ?? '' }}" class="mt-1 block w-full rounded-lg border-slate-200 text-sm"></label>
    <label class="text-xs font-semibold text-slate-500">Minimum amount<input inputmode="decimal" name="amount_min" value="{{ $filters['amount_min'] ?? '' }}" class="mt-1 block w-full rounded-lg border-slate-200 text-sm"></label>
    <label class="text-xs font-semibold text-slate-500">Maximum amount<input inputmode="decimal" name="amount_max" value="{{ $filters['amount_max'] ?? '' }}" class="mt-1 block w-full rounded-lg border-slate-200 text-sm"></label>
    <label class="text-xs font-semibold text-slate-500">Status<select name="workflow_status" class="mt-1 block w-full rounded-lg border-slate-200 text-sm"><option value="">All statuses</option>@foreach(['budget_requested', 'approved', 'released', 'in_progress', 'liquidated', 'closed', 'cancelled', 'draft', 'submitted', 'noted', 'Pending', 'Approved', 'Rejected'] as $status)<option @selected(($filters['workflow_status'] ?? '') === $status) value="{{ $status }}">{{ ucfirst(str_replace('_', ' ', $status)) }}</option>@endforeach</select></label>
    <div class="flex items-end gap-3"><button type="submit" class="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-700">Apply filters</button><a class="py-2 text-sm text-slate-500" href="{{ url()->current() }}">Reset</a></div>
    @if($errors->any())<p class="text-sm text-red-600 sm:col-span-2">{{ $errors->first() }}</p>@endif
</form>
