<x-accounting_app>
    <x-slot name="header">{{ \App\Services\AccountingWorkspace::SECTIONS[$section][0] }}</x-slot>
    <div class="space-y-6">
        <div><p class="text-xs font-bold uppercase tracking-widest text-blue-600">{{ $workflowCompany->name }} · Accounting</p><h1 class="mt-2 text-2xl font-bold">{{ \App\Services\AccountingWorkspace::SECTIONS[$section][0] }}</h1><p class="mt-2 text-sm text-slate-500">Company-scoped financial records and recorded workflow evidence.</p></div>
        @if(in_array($section, ['returned', 'missing', 'settlement', 'cash', 'expenses', 'documents', 'releases', 'audit', 'reports']))
            <div class="rounded-xl border border-blue-100 bg-blue-50 p-4 text-sm text-blue-900">{{ match($section) {
                'returned' => 'Ordinary Rejected records are visible here. Budget and travel return/rejection transitions need confirmed rules and remain disabled.',
                'missing' => 'Receipt flags and missing ordinary receipt references indicate documentation gaps. A travel receipt flag does not prove a file was uploaded or verified.',
                'settlement' => 'Approved travel records awaiting settlement or carrying a nonzero recorded balance. Payments and closure remain permission- and configuration-controlled.',
                'cash' => 'Ordinary petty cash reports use VND. Their PCF balance is a report calculation, not an authoritative cash ledger.',
                'expenses' => 'Expense details are stored on each ordinary or travel report. Open the report to inspect itemized expenses and payment methods.',
                'documents' => 'Only ordinary receipt files currently exist in the schema. Budget, travel, release and settlement attachments need an approved private-document model.',
                'releases' => 'Eligible approved requests already have an Accounting note. Actual payment recording requires confirmed currency and release rules; existing unquantified confirmations are distinguished on details.',
                'audit' => 'Append-only activities preserve actor snapshots and recorded transitions. Archived record history is retained; missing historical events are not reconstructed.',
                default => 'Financial reports use stored authoritative payment records and separate currencies. Requested budgets do not prove cash released.',
            } }}</div>
        @endif
        @if(in_array($section, ['reports', 'transactions'])) @include('accounting.summary') @endif
        @if($payments !== null)
            <section class="overflow-hidden rounded-2xl border bg-white"><h2 class="p-5 font-bold">Recorded fund releases</h2><div class="overflow-x-auto"><table class="w-full min-w-[650px] text-left text-sm"><thead class="bg-slate-50"><tr>@foreach(['Budget', 'Amount', 'Date', 'Method', 'Reference'] as $heading)<th class="p-3">{{ $heading }}</th>@endforeach</tr></thead><tbody>@forelse($payments as $payment)<tr class="border-t"><td class="p-3">{{ $payment->control_id }}</td><td class="p-3 font-mono">{{ $payment->currency }} {{ \Brick\Math\BigDecimal::of($payment->amount)->toScale(2) }}</td><td class="p-3">{{ $payment->released_at }}</td><td class="p-3">{{ $payment->payment_method }}</td><td class="p-3">{{ $payment->reference_no }}</td></tr>@empty<tr><td class="p-5 text-slate-500" colspan="5">No recorded payments.</td></tr>@endforelse</tbody></table></div><div class="p-4">{{ $payments->links() }}</div></section>
        @endif
        @if($settlements !== null)
            <section class="overflow-hidden rounded-2xl border bg-white"><h2 class="p-5 font-bold">Recorded settlement payments</h2><div class="overflow-x-auto"><table class="w-full min-w-[750px] text-left text-sm"><thead class="bg-slate-50"><tr>@foreach(['Travel ID', 'Currency', 'Employee return', 'Company reimbursement', 'Outstanding', 'Reference'] as $heading)<th class="p-3">{{ $heading }}</th>@endforeach</tr></thead><tbody>@forelse($settlements as $settlement)<tr class="border-t"><td class="p-3">#{{ $settlement->liquidation_id }}</td><td class="p-3">{{ $settlement->currency }}</td>@foreach(['employee_return_amount', 'company_reimbursement_amount', 'outstanding_balance'] as $field)<td class="p-3 font-mono">{{ \Brick\Math\BigDecimal::of($settlement->$field)->toScale(2) }}</td>@endforeach<td class="p-3">{{ $settlement->reference_no }}</td></tr>@empty<tr><td colspan="6" class="p-5 text-slate-500">No recorded settlements.</td></tr>@endforelse</tbody></table></div><div class="p-4">{{ $settlements->links() }}</div></section>
        @endif
        @if($documents !== null)
            <section class="rounded-2xl border bg-white p-5"><h2 class="font-bold">Private receipt index</h2><ul class="mt-4 divide-y">@forelse($documents as $item)<li class="flex flex-wrap justify-between gap-3 py-3 text-sm"><span>{{ $item->ref_no }} · {{ $item->payee }} · {{ $item->report->preparer?->name }}</span><a class="font-semibold text-blue-700" href="{{ route('liquidation.receipt', $item) }}">Open authorized receipt →</a></li>@empty<li class="py-4 text-sm text-slate-500">No receipt files recorded.</li>@endforelse</ul>{{ $documents->links() }}</section>
        @endif
        @if($expenses !== null)
            <section class="overflow-hidden rounded-2xl border bg-white"><h2 class="p-5 font-bold">Itemized expense records</h2><div class="overflow-x-auto"><table class="w-full min-w-[800px] text-left text-xs"><thead class="bg-slate-50"><tr>@foreach(['Report', 'Date', 'Category', 'Description', 'Amount', 'Receipt', 'Actions'] as $heading)<th class="p-3">{{ $heading }}</th>@endforeach</tr></thead><tbody>@forelse($expenses as $expense)<tr class="border-t"><td class="p-3">{{ $expense->reference }} · {{ $expense->type }}</td><td class="p-3">{{ $expense->expense_date ?? 'Not recorded' }}</td><td class="p-3">{{ $expense->category }}</td><td class="p-3">{{ $expense->description }}</td><td class="p-3 font-mono">{{ $expense->currency }} {{ \Brick\Math\BigDecimal::of($expense->amount)->toScale(2) }}</td><td class="p-3">{{ $expense->receipt }}</td><td class="p-3"><a class="text-blue-700" href="{{ route($expense->type === 'ordinary' ? 'accounting.mi.liquidation.show' : 'accounting.mi.travel.show', $expense->parent_id) }}">View report →</a></td></tr>@empty<tr><td class="p-5 text-slate-500" colspan="7">No itemized expenses match these filters.</td></tr>@endforelse</tbody></table></div><div class="p-4">{{ $expenses->links() }}</div></section>
        @endif
        @if($activities !== null)
            <section class="overflow-hidden rounded-2xl border bg-white"><h2 class="p-5 font-bold">Financial activity history</h2><div class="overflow-x-auto"><table class="w-full min-w-[1000px] text-left text-xs"><thead class="bg-slate-50"><tr>@foreach(['When', 'Record', 'Actor', 'Action', 'Transition', 'Amount / Reference', 'Comment'] as $heading)<th class="p-3">{{ $heading }}</th>@endforeach</tr></thead><tbody>@forelse($activities as $activity)<tr class="border-t"><td class="p-3">{{ $activity->created_at }}</td><td class="p-3">{{ $activity->record_type }} #{{ $activity->record_id }}</td><td class="p-3">{{ $activity->actor_name_snapshot }}<p class="text-slate-500">{{ $activity->actor_role_snapshot }}</p></td><td class="p-3">{{ str_replace('_', ' ', $activity->event) }}</td><td class="p-3">{{ $activity->previous_status ?? 'New' }} → {{ $activity->new_status }}</td><td class="p-3">{{ $activity->currency }} {{ $activity->amount }}<p>{{ $activity->reference_no }}</p></td><td class="p-3">{{ $activity->note }}</td></tr>@empty<tr><td colspan="7" class="p-5 text-slate-500">No recorded activity history.</td></tr>@endforelse</tbody></table></div><div class="p-4">{{ $activities->links() }}</div></section>
        @else
            <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">@include('accounting.filters') @include('accounting.rows')</section>
        @endif
    </div>
</x-accounting_app>
